{% set version = "0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggextra
  version: {{ version|replace("-", "_") }}

source:
  fn: ggExtra_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggExtra/ggExtra_{{ version }}.tar.gz
  sha256: f22db92d6e3e610901998348acbcaa6652fa6c62a285a622d3b962ba9e89aba2

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-colourpicker >=1.0
    - r-ggplot2 >=2.2.0
    - r-gtable >=0.2.0
    - r-miniui >=0.1.1
    - r-scales >=0.2.0
    - r-shiny >=0.13.0
    - r-shinyjs >=0.5.2
  run:
    - r-base
    - r-colourpicker >=1.0
    - r-ggplot2 >=2.2.0
    - r-gtable >=0.2.0
    - r-miniui >=0.1.1
    - r-scales >=0.2.0
    - r-shiny >=0.13.0
    - r-shinyjs >=0.5.2

test:
  commands:
    - $R -e "library('ggExtra')"           # [not win]
    - "\"%R%\" -e \"library('ggExtra')\""  # [win]

about:
  home: https://github.com/daattali/ggExtra
  license: MIT
  summary: Collection of functions and layers to enhance 'ggplot2'. The  flagship function is
    'ggMarginal()', which can be used to add marginal histograms/boxplots/density plots
    to 'ggplot2' scatterplots.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
