travis:
  secure:
    BINSTAR_TOKEN: wlOPU/EW4LQBdxMaZfvVDubIKUMK7yrSCVeGi401+4AY9hoJZjxwox3c9GTbSNIHB6HGSSSFv9nLHbrSrPd/9wmLHtSce0pOqS6PBijA13U2shT7J+gjWMXU77R7ITv61Hb0Kogapu7iSGPUF/PXnUGL91oCF5WwQIRbw0tLYFmRl5z3B0gb407ay3NwsCM/Q+3ii8cqRRs+Fg4CBrWjHH3hLLNSZnX+JNGr4a21vwsWQjQLPrN9crtWA41S8gEP5lgUNl0wnwjJur0IFObQ4uoRD8NFhQRvWWJPBY6QfFp437XJdClRIq7Fd0j7Xzx0cGV3FuRhpQh5KvvlMA7esFcRfh7VxOkMoiow9N2YyGW/gvwsqN9FnLihuDHGvUSqrdPakWChzq9vnoUlxKV/gGGJ9Z9LPcAJ1UPac2Po4UtXEpeZz+cC4fvCU7zslsXzbYBe0/hArkwmuhdfS154WmSYr6KE4wVtBUHZCEEwLiGqeeRXq8ZO77MccUbPqVQIzViMdRT+RNcHfQvYDwZFnyCpoAbU9EziINF/cgLSiOJgjwZIk9cNMbmK8AJT/RSICKrwKm+TgizQntJlUf7pbAEq5hma0/GkoACkvAz3Vw+A3Ha+Coko3JaV7Wfx08Y6qXTkJ7BsBBL3SrVhoIZ/FDJBvt76XAkzhmviAN+otXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
